### ISSUE TITLE
update known issues for some components

### ISSUE THREAD

**Issue by mariojmdavid** [deephdc/deep-releases#4]
the following components have open issues, but the corresponding rst say no known issues
https://github.com/indigo-dc/orchestrator/issues
https://github.com/EGI-Foundation/cloud-info-provider/issues
https://github.com/indigo-dc/udocker/issues

tell me if I can update this

**Comment by caifti** [comment]
So: the Known Issuse in the documentation are meant to present iportant issues for which we can recommend workarounds, so that a user can follow those workarounds in order to have a functional service. 
The list of open issues, continaing item like "Add support for deploying VMs with GPUs" or similar is not what I have in mind with the "known issues" section. let me know if It's more clear or .. let's talk.
I'll update accordingly the ones where ( by mistake) I've put the list of open issues.

**Comment by orviz** [comment]
> https://github.com/EGI-Foundation/cloud-info-provider/issues

agree with @caifti that not all the issues above affect the behaviour of the component, indeed most of them are enhancements. 

For the specific case of cloud-info-provider, the upstream repository might not be always the best reference. We could create specific ones in indigo-dc/cloud-info-provider-deep when needed.
